# .github/workflows/gh-pages.yml
name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main

# Explicit permissions so the workflow can push to the repository / pages branch
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # ensure the checkout step persists credentials so the GITHUB_TOKEN can be used for pushes
          persist-credentials: true
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install deps
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
